-- SQL to promote data from snapshot tables to canonical raw tables.
-- This script handles the mapping from JSONB raw_payload to structured columns.
-- Strategy: Only promote CURRENT SEASON (2026) rows for daily updates.

-- 1. Promote Player Identity Snapshots
-- Source: tbc_players_feed_snapshots (Identity feed)
-- Target: tbc_players_raw
INSERT INTO tbc_players_raw (
    playerid, firstname, lastname, highlevel, ht, wt, bats, throws, posit, 
    borndate, currentage, place, high_school
)
SELECT 
    (raw_payload->>'playerid')::TEXT,
    (raw_payload->>'firstname')::TEXT,
    (raw_payload->>'lastname')::TEXT,
    (raw_payload->>'highlevel')::TEXT,
    (raw_payload->>'ht')::TEXT,
    (raw_payload->>'wt')::TEXT,
    (raw_payload->>'bats')::TEXT,
    (raw_payload->>'throws')::TEXT,
    (raw_payload->>'posit')::TEXT,
    (raw_payload->>'borndate')::TEXT,
    (raw_payload->>'currentage')::NUMERIC,
    (raw_payload->>'place')::TEXT,
    (raw_payload->>'high_school')::TEXT
FROM tbc_players_feed_snapshots
WHERE snapshot_date = CURRENT_DATE
ON CONFLICT (playerid) DO UPDATE SET
    firstname = EXCLUDED.firstname,
    lastname = EXCLUDED.lastname,
    highlevel = EXCLUDED.highlevel,
    ht = EXCLUDED.ht,
    wt = EXCLUDED.wt,
    bats = EXCLUDED.bats,
    throws = EXCLUDED.throws,
    posit = EXCLUDED.posit,
    borndate = EXCLUDED.borndate,
    currentage = EXCLUDED.currentage,
    place = EXCLUDED.place,
    high_school = EXCLUDED.high_school;

-- 2. Promote Batting Stats Snapshots
-- Source: tbc_batting_feed_snapshots (Batting stats feed)
-- Target: tbc_batting_raw
-- Filter: Only year 2026
INSERT INTO tbc_batting_raw (
    teamid, playerid, year, uniform, playername, age, ba, th, class, posit, 
    g, ab, r, h, dbl, tpl, hr, rbi, sb, cs, bb, so, hbp, sh, sf, ibb, gdp, 
    tb, pa, xbh, sgl, bavg, obp, slg, ops, seca, iso, babip, bb_pct, so_pct, 
    so_bb, ab_hr, highlevel, mlbyears, playyears, draft_info
)
SELECT 
    (raw_payload->>'teamid')::INTEGER,
    (raw_payload->>'playerid')::TEXT,
    (raw_payload->>'year')::INTEGER,
    (raw_payload->>'uniform')::TEXT,
    (raw_payload->>'playername')::TEXT,
    (raw_payload->>'age')::INTEGER,
    (raw_payload->>'ba')::TEXT,
    (raw_payload->>'th')::TEXT,
    (raw_payload->>'class')::TEXT,
    (raw_payload->>'posit')::TEXT,
    (raw_payload->>'g')::INTEGER,
    (raw_payload->>'ab')::INTEGER,
    (raw_payload->>'r')::INTEGER,
    (raw_payload->>'h')::INTEGER,
    (raw_payload->>'dbl')::INTEGER,
    (raw_payload->>'tpl')::INTEGER,
    (raw_payload->>'hr')::INTEGER,
    (raw_payload->>'rbi')::INTEGER,
    (raw_payload->>'sb')::INTEGER,
    (raw_payload->>'cs')::INTEGER,
    (raw_payload->>'bb')::INTEGER,
    (raw_payload->>'so')::INTEGER,
    (raw_payload->>'hbp')::INTEGER,
    (raw_payload->>'sh')::INTEGER,
    (raw_payload->>'sf')::INTEGER,
    (raw_payload->>'ibb')::INTEGER,
    (raw_payload->>'gdp')::INTEGER,
    (raw_payload->>'tb')::INTEGER,
    (raw_payload->>'pa')::INTEGER,
    (raw_payload->>'xbh')::INTEGER,
    (raw_payload->>'sgl')::INTEGER,
    (raw_payload->>'bavg')::NUMERIC,
    (raw_payload->>'obp')::NUMERIC,
    (raw_payload->>'slg')::NUMERIC,
    (raw_payload->>'ops')::NUMERIC,
    (raw_payload->>'seca')::NUMERIC,
    (raw_payload->>'iso')::NUMERIC,
    (raw_payload->>'babip')::NUMERIC,
    (raw_payload->>'bb_pct')::NUMERIC,
    (raw_payload->>'so_pct')::NUMERIC,
    (raw_payload->>'so_bb')::NUMERIC,
    (raw_payload->>'ab_hr')::NUMERIC,
    (raw_payload->>'highlevel')::TEXT,
    (raw_payload->>'mlbyears')::TEXT,
    (raw_payload->>'playyears')::TEXT,
    (raw_payload->>'draft_info')::TEXT
FROM tbc_batting_feed_snapshots
WHERE snapshot_date = CURRENT_DATE
  AND (raw_payload->>'year')::INTEGER = 2026
ON CONFLICT (playerid, year, teamid) DO UPDATE SET
    uniform = EXCLUDED.uniform,
    playername = EXCLUDED.playername,
    age = EXCLUDED.age,
    ba = EXCLUDED.ba,
    th = EXCLUDED.th,
    class = EXCLUDED.class,
    posit = EXCLUDED.posit,
    g = EXCLUDED.g,
    ab = EXCLUDED.ab,
    r = EXCLUDED.r,
    h = EXCLUDED.h,
    dbl = EXCLUDED.dbl,
    tpl = EXCLUDED.tpl,
    hr = EXCLUDED.hr,
    rbi = EXCLUDED.rbi,
    sb = EXCLUDED.sb,
    cs = EXCLUDED.cs,
    bb = EXCLUDED.bb,
    so = EXCLUDED.so,
    hbp = EXCLUDED.hbp,
    sh = EXCLUDED.sh,
    sf = EXCLUDED.sf,
    ibb = EXCLUDED.ibb,
    gdp = EXCLUDED.gdp,
    tb = EXCLUDED.tb,
    pa = EXCLUDED.pa,
    xbh = EXCLUDED.xbh,
    sgl = EXCLUDED.sgl,
    bavg = EXCLUDED.bavg,
    obp = EXCLUDED.obp,
    slg = EXCLUDED.slg,
    ops = EXCLUDED.ops,
    seca = EXCLUDED.seca,
    iso = EXCLUDED.iso,
    babip = EXCLUDED.babip,
    bb_pct = EXCLUDED.bb_pct,
    so_pct = EXCLUDED.so_pct,
    so_bb = EXCLUDED.so_bb,
    ab_hr = EXCLUDED.ab_hr,
    highlevel = EXCLUDED.highlevel,
    mlbyears = EXCLUDED.mlbyears,
    playyears = EXCLUDED.playyears,
    draft_info = EXCLUDED.draft_info;

-- 3. Promote Pitching Stats Snapshots
-- Source: tbc_pitching_feed_snapshots (Pitching stats feed)
-- Target: tbc_pitching_raw
-- Filter: Only year 2026
INSERT INTO tbc_pitching_raw (
    teamid, playerid, year, uniform, playername, age, ba, th, class, 
    w, l, g, gs, cg, sho, gr, gf, sv, ip, h, r, er, hr, bb, so, wp, bk, hb, 
    era, whip, h9, hr9, bb9, so9, ra9, so_bb, highlevel, mlbyears, playyears, draft_info
)
SELECT 
    (raw_payload->>'teamid')::INTEGER,
    (raw_payload->>'playerid')::TEXT,
    (raw_payload->>'year')::INTEGER,
    (raw_payload->>'uniform')::TEXT,
    (raw_payload->>'playername')::TEXT,
    (raw_payload->>'age')::INTEGER,
    (raw_payload->>'ba')::TEXT,
    (raw_payload->>'th')::TEXT,
    (raw_payload->>'class')::TEXT,
    (raw_payload->>'w')::INTEGER,
    (raw_payload->>'l')::INTEGER,
    (raw_payload->>'g')::INTEGER,
    (raw_payload->>'gs')::INTEGER,
    (raw_payload->>'cg')::INTEGER,
    (raw_payload->>'sho')::INTEGER,
    (raw_payload->>'gr')::INTEGER,
    (raw_payload->>'gf')::INTEGER,
    (raw_payload->>'sv')::INTEGER,
    (raw_payload->>'ip')::NUMERIC,
    (raw_payload->>'h')::INTEGER,
    (raw_payload->>'r')::INTEGER,
    (raw_payload->>'er')::INTEGER,
    (raw_payload->>'hr')::INTEGER,
    (raw_payload->>'bb')::INTEGER,
    (raw_payload->>'so')::INTEGER,
    (raw_payload->>'wp')::INTEGER,
    (raw_payload->>'bk')::INTEGER,
    (raw_payload->>'hb')::INTEGER,
    (raw_payload->>'era')::NUMERIC,
    (raw_payload->>'whip')::NUMERIC,
    (raw_payload->>'h9')::NUMERIC,
    (raw_payload->>'hr9')::NUMERIC,
    (raw_payload->>'bb9')::NUMERIC,
    (raw_payload->>'so9')::NUMERIC,
    (raw_payload->>'ra9')::NUMERIC,
    (raw_payload->>'so_bb')::NUMERIC,
    (raw_payload->>'highlevel')::TEXT,
    (raw_payload->>'mlbyears')::TEXT,
    (raw_payload->>'playyears')::TEXT,
    (raw_payload->>'draft_info')::TEXT
FROM tbc_pitching_feed_snapshots
WHERE snapshot_date = CURRENT_DATE
  AND (raw_payload->>'year')::INTEGER = 2026
ON CONFLICT (playerid, year, teamid) DO UPDATE SET
    uniform = EXCLUDED.uniform,
    playername = EXCLUDED.playername,
    age = EXCLUDED.age,
    ba = EXCLUDED.ba,
    th = EXCLUDED.th,
    class = EXCLUDED.class,
    w = EXCLUDED.w,
    l = EXCLUDED.l,
    g = EXCLUDED.g,
    gs = EXCLUDED.gs,
    cg = EXCLUDED.cg,
    sho = EXCLUDED.sho,
    gr = EXCLUDED.gr,
    gf = EXCLUDED.gf,
    sv = EXCLUDED.sv,
    ip = EXCLUDED.ip,
    h = EXCLUDED.h,
    r = EXCLUDED.r,
    er = EXCLUDED.er,
    hr = EXCLUDED.hr,
    bb = EXCLUDED.bb,
    so = EXCLUDED.so,
    wp = EXCLUDED.wp,
    bk = EXCLUDED.bk,
    hb = EXCLUDED.hb,
    era = EXCLUDED.era,
    whip = EXCLUDED.whip,
    h9 = EXCLUDED.h9,
    hr9 = EXCLUDED.hr9,
    bb9 = EXCLUDED.bb9,
    so9 = EXCLUDED.so9,
    ra9 = EXCLUDED.ra9,
    so_bb = EXCLUDED.so_bb,
    highlevel = EXCLUDED.highlevel,
    mlbyears = EXCLUDED.mlbyears,
    playyears = EXCLUDED.playyears,
    draft_info = EXCLUDED.draft_info;
